name: Run benchmarks

on:
  workflow_call:
  workflow_dispatch:

jobs:
  permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the
    # added or changed files to the repository.
    contents: write
  benchmark:
    runs-on: ubuntu-latest
    steps:
      # Always checkout master branch, even if triggered by a tag.
      # Otherwise sphinx-multiversion does not pull the master branch.
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Checkout benchmarks
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .asv/
          ref: benchmarks
          path: .asv/

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install versioned-hdf5
        run: |
          pip install '.[bench]'

      - name: Update git tags for benchmarking
        run: |
          git fetch --tags

      - name: Run benchmarks on new commits
        run: |
          asv machine --machine gh-runner --yes

          # Run on all tags, and any commit since 1.7.0
          for ref in $(git tag) $(git rev-list 1.7.0..HEAD); do
            asv run --machine gh-runner $ref --skip-existing --show-stderr NEW
          done

      - name: Show results
        run: |
          asv show

      - name: Auto-commit to benchmarks branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated benchmarks
          branch: benchmarks
          file_pattern: .asv/
          add_options: '-f'
