name: Run benchmarks

on:
  push:
    branches: ["master"]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the
    # added or changed files to the repository.
    contents: write
  benchmark:
    runs-on: ubuntu-latest
    steps:
      # Always checkout master branch, even if triggered by a tag.
      # Otherwise sphinx-multiversion does not pull the master branch.
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install versioned-hdf5
        run: |
          pip install .[bench]

      - name: Run benchmarks on new commits
        run: |
          asv run --machine gh-runner -e NEW

      - name: Show results
        run: |
          asv show

      - name: Publish results
        run: |
          asv publish
          rm -r benchmarks
          mv .asv/html benchmark_results

      - name: Auto-commit to benchmarks branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated benchmarks
          branch: benchmarks
          file_pattern: benchmark_results/
