name: Benchmarks

on: [workflow_call, workflow_dispatch]

jobs:
  run-benchmarks:
    runs-on: "cirun-benchmark-runner--${{ github.run_id }}"
    steps:
      # Install git first; otherwise actions/checkout silently falls back
      # to github REST API for downloading the repo
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install git build-essential pkg-config libhdf5-dev mpi-default-dev -y

      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup python with miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11

      - uses: mxschmitt/action-tmate@v3

      # Pin ndindex to avoid bug with 1.9.1
      # Pin h5py to development version to avoid
      #   ValueError: Could not get virtual filename
      # in 3.11.0
      - name: Install versioned-hdf5
        run: |
          conda install pip -y
          pip install '.[bench]' ndindex==1.8 git+https://github.com/h5py/h5py.git@761e238d41c512086a7f887976e01d49a030621d

      # Compare the most recent commit with the previous one
      - name: Run benchmarks
        run: |
          asv machine --yes
          asv continuous HEAD^ HEAD

      - name: Checkout benchmarks
        run: |
          git stash
          git fetch origin benchmarks
          git checkout benchmarks --
          git stash pop

      - name: Add and commit benchmarks
        run: |
          git add .asv/
          git commit -n -m "Update benchmarks for commit ${{ github.event.pull_request.head.sha }}"
          git push origin benchmarks
