name: Release Python Bindings to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      test_pypi:
        type: boolean
        description: 'Test release: publish on test.pypi.org'
        default: false

jobs:
  build-sdist:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: 💻 Checkout the repo
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: conda-incubator/setup-miniconda@v3.1.0 # v3.1.0
        with:
          auto-update-conda: true
          python-version: "3.11"
          activate-environment: "build"
          channels: conda-forge

      - name: Install native dependencies
        run: |
          conda install -y hdf5tools hdf5 openmpi


      - name: 🚀 Install build dependencies
        run: |
          pip install build twine

      - name: 📦 Build the sdist and wheel
        run: |
          python -m build --sdist -o wheelhouse

      - name: List and check sdist
        run: |
          ls -lh wheelhouse/
          twine check wheelhouse/*

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: ./wheelhouse/*.tar.gz

  build-wheels:
    name: >
      build ${{ matrix.python-version }} on ${{ matrix.platform || matrix.os }}
      ${{ (matrix.arch) || '' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        python-version: ['cp312', 'cp311']
        include:
          - os: ubuntu
            platform: linux
          - os: windows
            ls: dir

    runs-on: ${{ format('{0}-latest', matrix.os) }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Build ${{ matrix.platform || matrix.os }} binaries
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_BUILD: '${{ matrix.python-version }}-*'
        # rust doesn't seem to be available for musl linux on i686
        CIBW_SKIP: '*-musllinux_i686'
        # we build for matrix.arch (only exists on macos), else 'auto'
        CIBW_ARCHS: ${{ matrix.arch || 'auto' }}
        CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH" CARGO_TERM_COLOR="always"'
        CIBW_ENVIRONMENT_WINDOWS: 'PATH="$UserProfile\.cargo\bin;$PATH"'
        CIBW_BEFORE_BUILD: rustup show
        # Linux wheels are built in manylinux containers; set up rust toolchain here
        CIBW_BEFORE_BUILD_LINUX: >
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=minimal -y &&
          rustup show
        CIBW_BUILD_VERBOSITY: 1

    - name: List and check wheels
      run: |
        pip install twine pkginfo>=1.10.0
        ${{ matrix.ls || 'ls -lh' }} wheelhouse/
        twine check wheelhouse/*

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.python-version }}
        path: ./wheelhouse/*.whl

  publish:
    name: Publish Python packages on PyPI
    needs: [build-sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/versioned-hdf5
    permissions:
      id-token: write
    steps:
      - name: Retrieve wheels and sdist
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: wheels/

      - name: print artifacts
        run: |
          ls -l wheels/

      - name: 🧪 Publish to PyPI Testing
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ inputs.test_pypi }}
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: wheels

      - name: 🎉 Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ !inputs.test_pypi }}
        with:
          packages-dir: wheels
